[2025-06-09T12:23:55.769+0200] {processor.py:157} INFO - Started process (PID=77346) to work on /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:23:55.771+0200] {processor.py:829} INFO - Processing file /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-09T12:23:55.774+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:23:55.773+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:23:55.783+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:23:55.782+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-09T12:23:55.784+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:23:55.784+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-09T12:23:55.784+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:23:55.809+0200] {processor.py:179} INFO - Processing /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-06-09T12:25:04.415+0200] {processor.py:157} INFO - Started process (PID=77798) to work on /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:25:04.416+0200] {processor.py:829} INFO - Processing file /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-09T12:25:04.417+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:25:04.416+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:25:04.421+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:25:04.420+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-09T12:25:04.421+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:25:04.421+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-09T12:25:04.422+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:25:04.449+0200] {processor.py:179} INFO - Processing /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-06-09T12:26:00.219+0200] {processor.py:157} INFO - Started process (PID=78223) to work on /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:26:00.220+0200] {processor.py:829} INFO - Processing file /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-09T12:26:00.221+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:26:00.221+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:26:00.225+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:26:00.224+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-09T12:26:00.225+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:26:00.225+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-09T12:26:00.225+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:26:00.247+0200] {processor.py:179} INFO - Processing /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-06-09T12:27:38.383+0200] {processor.py:157} INFO - Started process (PID=78900) to work on /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:27:38.385+0200] {processor.py:829} INFO - Processing file /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-09T12:27:38.388+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:27:38.387+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:27:38.399+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:27:38.396+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-09T12:27:38.399+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:27:38.399+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-09T12:27:38.400+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:27:38.453+0200] {processor.py:179} INFO - Processing /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2025-06-09T12:41:51.315+0200] {processor.py:157} INFO - Started process (PID=90597) to work on /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:41:51.316+0200] {processor.py:829} INFO - Processing file /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-09T12:41:51.317+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:41:51.316+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:41:51.321+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:41:51.320+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-09T12:41:51.321+0200] {logging_mixin.py:154} INFO - [2025-06-09T12:41:51.321+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-09T12:41:51.321+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-09T12:41:51.345+0200] {processor.py:179} INFO - Processing /home/diego.rivero/practica_creativa/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
